[package]
name = "vuvuzella"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
chacha20poly1305 = "0.10.1"
x25519-dalek = "2.0.1"
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }
